driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true
  customize:
    memory: 2048

platforms:
  - name: ubuntu-10.04
    run_list:
      - recipe[apt]
  - name: ubuntu-12.04
    run_list:
      - recipe[apt]
  - name: ubuntu-14.04
    run_list:
      - recipe[apt]
  - name: centos-5.10
  - name: centos-6.5

suites:
  - name: package
    run_list:
      - recipe[tmux::default]
    attributes:
      tmux:
        install_method: package
    excludes:
      - centos-6.5
      - centos-5.10
  - name: source
    run_list:
      - recipe[tmux::default]
    attributes:
      tmux:
        install_method: source
